/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package it.cnr.isti.hpc.wikipedia.article;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum Type {
  BODY, TABLE, LIST, IMAGE, UNKNOWN, CATEGORY  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"Type\",\"namespace\":\"it.cnr.isti.hpc.wikipedia.article\",\"symbols\":[\"BODY\",\"TABLE\",\"LIST\",\"IMAGE\",\"UNKNOWN\",\"CATEGORY\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
